# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1aee47ef62ba53e4d7373567c64ebefce369ca0ec131cc57da691c53ee8a7ea3ba1b8d9ebdf1ed6afbb443eb1b3984bcc233d02f74dabb0b983e5b2b430dbb0b

test:
  secret_key_base: 6c2e3d50580040d704187fdecfad8ed169b101930db12a2a6f0f4168485b111bad1c40aada0d0e02d90606b1c1dd3481e7a6003b2d2c5e2290456032dc8dcc36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
